### ISSUE TITLE
Not able to install due to a python problem

### ISSUE THREAD

**Issue by ghtmtt** [ebrelsford/qgis-projestions#1]
Hi,

I'm really interested in your plugin, but I'm not able to install it:

`The plugin is broken. Python said: no module named settings`

do you have any suggestion?

QGIS 2.14 on an Ubuntu 16.04 machine

Thanks

**Comment by ebrelsford** [comment]
Yes I noticed this, too. Thanks for pointing it out.

There is a fix in [v0.1.1](http://plugins.qgis.org/plugins/Projestions/version/0.1.1/), just waiting for it to be approved.

**Comment by ebrelsford** [comment]
@ghtmtt `0.1.1` is in the QGIS plugins repository now, so you should be able to install it.
