### ISSUE TITLE
crashing qgis

### ISSUE THREAD

**Issue by antoniusz** [ebrelsford/qgis-projestions#4]
Hi,

Qgis (master_2) crashing with the following message, when i want to use your plugin:

**with active layer extent**

Warning: QPixmap: It is not safe to use pixmaps outside the GUI thread
...
Warning: QObject::setParent: Cannot set parent, new parent is in a different thread
...
Warning: QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
...
Warning: QObject::setParent: Cannot set parent, new parent is in a different thread
...
Warning: QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
Segmentation fault

**with map canvas extent**

Warning: QPixmap: It is not safe to use pixmaps outside the GUI thread
...
Warning: QObject::setParent: Cannot set parent, new parent is in a different thread
...
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
qgis: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Félbeszakítva (Aborted)

**Comment by ebrelsford** [comment]
Thanks for letting me know, @antoniusz, I'm looking into it. Seems to be an issue on 2.16 as well, which is a little surprising.

**Comment by ebrelsford** [comment]
@antoniusz: The API changed slightly and broke the plugin, `v0.1.2` should take care of it. I'll post here when it's in the plugin repository.

**Comment by ebrelsford** [comment]
@antoniusz: `v0.1.2` is in the plugin repository now, would you mind upgrading it and seeing if it works now?

**Comment by antoniusz** [comment]
Yes, it works. Thank you very much.
