### ISSUE TITLE
Please put plugin under `Plugins` menu

### ISSUE THREAD

**Issue by pcav** [ebrelsford/qgis-projestions#5]
The plugin is shown only in the toolbar. Please add an entry also in the dropdown menu.

**Comment by pcav** [comment]
Sorry, it is not only in the toolbar, but also under `Web` menu. It seems more appropriate for the Plugins, as for similar ones.

**Comment by ebrelsford** [comment]
Sure, that works for me. Originally I had placed it under `Web` because it uses an online API, but that seems less natural now.
