### ISSUE TITLE
Error with QGIS3: AttributeError: 'QgsMessageLog' object has no attribute 'WARNING'

### ISSUE THREAD

**Issue by rogorido** [ebrelsford/qgis-projestions#6]
Thanks for the plugin. I'm getting the following error with qgis3:

Traceback (most recent call last):
			  File "/home/igor/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Projestion/projestions.py", line 151, in run
			    level=QgsApplication.instance().messageLog().WARNING)
			AttributeError: 'QgsMessageLog' object has no attribute 'WARNING'

**Comment by ebrelsford** [comment]
Thanks @rogorido, that must have been a relatively late change for QGIS 3. I've fixed it and will be pushing a new version to the plugin repository.

**Comment by rogorido** [comment]
thanks!
