### ISSUE TITLE
Plugin error in QGIS 3.4

### ISSUE THREAD

**Issue by ghtmtt** [ebrelsford/qgis-projestions#8]
I get this error on Linux (Debian) with QGIS 3.4 installed:

```
Traceback (most recent call last):
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/corso_pisa/python/plugins/Projestions/projestions.py", line 337, in run
    item = self.dlg.crsTableView.selectionModel().selectedRows()[0]
AttributeError: 'NoneType' object has no attribute 'selectedRows'
```

**Comment by ebrelsford** [comment]
Thanks @ghtmtt. Can you please confirm that you're using version `0.4.2` of the plugin? Thanks!

**Comment by ghtmtt** [comment]
yep, version 0.4.2. Actually in QGIS master (3.7), when installing I get this new error now:

```
An error occurred during execution of following code:
pyplugin_installer.instance().installPlugin('Projestions')


traceback.print_exception() failed

Python version:


QGIS version:
3.7.0-Master 'Master', b2aa97843d

Python path:
```

**Comment by ebrelsford** [comment]
@ghtmtt I tried with QGIS 3.7 to re-install the plugin and it is working fine on this end, are there any other details you can provide to help debug?

**Comment by ghtmtt** [comment]
reinstalled and works fine, thanks!
