### ISSUE TITLE
world_map.shp not in resources anymore

### ISSUE THREAD

**Issue by i-s-o** [ebrelsford/qgis-projestions#9]
In QGIS 3.10 (Win10), I get the following message in DebugView++ (also, an equivalent warning message shows up in the log messages panel, under OGR tab):

`..\..\..\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [0ms] 2019-12-29T15:58:11 OGR[1] Cannot open C:/tools/OSGeo4W64/apps/qgis-rel-dev/./resources/data/world_map.shp.()`

This is due to [PR 30647](https://github.com/qgis/QGIS/pull/30647) and some followup/backport commits.

Changing `world_map.shp` to `world_map.gpkg|layername=countries` in the following line fixes the issue for me:

https://github.com/ebrelsford/qgis-projestions/blob/deb1f2e60c9a2ac74dffbb433bf344aaa5e4d00a/projestions_dialog.py#L52

**Comment by ebrelsford** [comment]
Thanks for letting me know, @i-s-o, I'm working on a new release to account for this.

**Comment by ebrelsford** [comment]
This [release](http://plugins.qgis.org/plugins/Projestions/version/1.0.1/) has been approved, thanks again for raising the issue, @i-s-o!
